---
title: "How Many Cats = One Human?"
author: "Matt C"
date: "2021-12-02"
slug: "Neural Networks"
tags:
- "Neural Networks"
- Nuerons
- Chart
output:
  html_document: default
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### How Many Cats = One Human? Or so what do we know about Neurons anyway.

Have you ever wondered how smart your cat or dog is? 

*Haha, I always do.* 


To be fair and add context, I was reading about Neural Networks. In many academic articles, the writer launches into a description of the model neuron. How it works. Its size. Its morphology and *Oh, by the way,* that's all we know about the brain or even the neuron.

As a scientist, I started to wonder how accurate is this picture. How many neurons does one person have? For that matter, how many neurons do humans AND animals have? 

You shouldn't be surprised to learn; the world has that information. Volumes and masses estimates have been known for decades. But some of the first studies on the number of neurons were only made in circa 1975. [^1]

Isn't it amazing that humans have known about farming and tools between 7,000-10,000 years. While, study of the human brain has only occurred in the last 20 years?  

**Looking at Table 1**: Organisms Vs. The number Of Neuronal Cells, it is easy to see that humans have the most Neuronal Cells of any animal. But is that all there is to how smart we are?

[^1]:Lange, W. 1975 Cell number and cell density in the cerebellar cortex of man and other mammals. Cell Tiss. Res. 157: 115–24

### Table 1: Organisms Vs Number Of Neuronal Cells

| Organism               |   Common Name | Approx. Number of Neurons | Ratio to Human |
| :--------------------- | ------------: | ------------------------: | -------------: |
| Homo sapien sapien     | modern humans |           100,000,000,000 |              1 |
| Canis lupus familiaris |           dog |             2,300,000,000 |             44 |
| Felis silvestris       |           cat |               760,000,000 |            130 |
| Mus musculus           |         mouse |                71,000,000 |          1,400 |
| Apis linnaeus          |     honey bee |                   960,000 |     10,000,000 |
| Chrysaora fuscescens   |     jellyfish |                     5,600 |     18,000,000 |
| Caenorhabditis elegans |     roundworm |                       302 |    330,000,000 |

Table 1: Organisms Vs Number Of Neuronal Cells [^2] [^3] [^4]

---

**One more thing**, Using this chart as a guide, humans should be 44 times smarter than dogs and 130 times smarter than cats. 

That makes me feel better all ready.


[^2]:[Wikipedia](https://en.wikipedia.org/wiki/List_of_animals_by_number_of_neurons)

[^3]:https://www.wormatlas.org/hermaphrodite/nervous/Neuroframeset.html

[^4]:Shepherd, G. M. (2004), The synaptic organization of the brain (5th ed.), Oxford University Press, New York.
